export default [
    { path: '/busquedaCertCatasUrb', 
      component: () => import('@/components/reportes/BusquedaCertificadoCatastral.vue'), 
      meta: { requiresAuth: true } },
    { path: '/busquedaCertCatasRur', 
      component: () => import('@/components/reportes/BusquedaCertificadoCatastralRur.vue'), 
      meta: { requiresAuth: true } },
    { path: '/busquedaCertPlusvalia', 
      component: () => import('@/components/reportes/BusquedaCertificadoPlusvalia.vue'), 
      meta: { requiresAuth: true } },
    { path: '/certificado-catastral-rur', 
      component: () => import('@/components/reportes/CertificadoCatastralRur.vue'), 
      meta: { requiresAuth: true } },
    { path: '/certificado-catastral', 
      component: () => import('@/components/reportes/CertificadoCatastralUrb.vue'), 
      meta: { requiresAuth: true } },    
    { path: '/certificado-plusvalia', 
      component: () => import('@/components/reportes/CertificadoPlusvaliaUrb.vue'), 
      meta: { requiresAuth: true } },
    { path: '/impresion-ficha', 
      component: () => import('@/components/reportes/FichaPredialUrbana.vue'), 
      meta: { requiresAuth: true } },
    { path: '/linderos-certificado', 
      component: () => import('@/components/reportes/LinderosCertificado.vue'), 
      meta: { requiresAuth: false } },
    { path: '/genera-certificados', 
      component: () => import('@/components/reportes/GeneraCertificados.vue'), 
      meta: { requiresAuth: true } },
    { path: '/certificado-base', 
      component: () => import('@/components/reportes/CertificadoBase.vue'), 
      meta: { requiresAuth: true } }
  ];
