version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: cayambe-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - backend/.env.production
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: cayambe-frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: cayambe-nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
