version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: cayambe-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: cayambe-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
